### ISSUE TITLE
New Streamlit update today breaks st-pages

### ISSUE THREAD

**Issue by Sprocketer** [blackary/st_pages#102]
Install and try - gets an error @blackary

**Comment by sfc-gh-trichards** [comment]
hey, what error do you get?

**Comment by Sprocketer** [comment]
@sfc-gh-trichards 
```
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/workspaces/BPhO-Computational/streamlit_app.py", line 18, in <module>
    show_pages_from_config()
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py", line 408, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/codespace/.local/lib/python3.10/site-packages/st_pages/__init__.py", line 308, in _show_pages_from_config
    show_pages(pages)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py", line 408, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/codespace/.local/lib/python3.10/site-packages/st_pages/__init__.py", line 252, in _show_pages
    rt._sources_watcher = LocalSourcesWatcher(rt._main_script_path)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/streamlit/watcher/local_sources_watcher.py", line 51, in __init__
    self._main_script_path = os.path.abspath(self._pages_manager.main_script_path)
AttributeError: 'str' object has no attribute 'main_script_path'
```

**Comment by Sprocketer** [comment]
Actually nevermind I just updated st-pages and it works fine again
