### ISSUE TITLE
Error if you switch too fast after reloading page in browser

### ISSUE THREAD

**Issue by Sprocketer** [blackary/st_pages#106]
```
IndexError: list index out of range
Exception in thread ScriptRunner.scriptThread:
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 309, in _run_script_thread
    self._run_script(request.rerun_data)
  File "C:\Program Files\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 434, in _run_script
    active_script = self._pages_manager.get_initial_active_script(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\streamlit\runtime\pages_manager.py", line 305, in get_initial_active_script
    return self.pages_strategy.get_initial_active_script(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\streamlit\runtime\pages_manager.py", line 114, in get_initial_active_script
    main_page_info = list(pages.values())[0]
                     ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by Sprocketer** [comment]
Probably something to do with a promise that isn't fulfilled before you check indices
